name: release

on:
  workflow_dispatch: {}
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: create file
        run: echo "this is a test!" > afile.txt
        
      - name: Format
        id: format
        uses: actions/github-script@v3
        with:
          result-encoding: string
          script: |
            const fs = require('fs').promises;
            console.log(fs);
            
            var content = await fs.readFile("afile.txt");
            console.log(content);
            
            return content;

      - name: display result
        run: echo ${{ steps.format.outputs.result }}
