name: release

on:
  workflow_dispatch: {}
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        
      - name: test
        run: |
          more $NPM_CONFIG_USERCONFIG
          npm whoami
        env:
          NODE_AUTH_TOKEN:  ${{ secrets.NPM_TOKEN }}
